# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwax4mFEXKi4FueK2C6awGy3Ftu3RGjd
"""

!pip install streamlit
!pip install joblib

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# Load the trained model
model = joblib.load("power_consumption_model.pkl")

st.title("🔌 Power Consumption Predictor")

st.markdown("Enter the input features below to predict power consumption (kWh).")

# --- Example Inputs (Add more depending on your final model features) ---

hour_of_day = st.slider("Hour of Day", 0, 23, 12)
temperature_c = st.number_input("Temperature (°C)", value=25.0)
humidity_pct = st.number_input("Humidity (%)", value=50.0)
solar_installed = st.selectbox("Solar Installed", ["Yes", "No"])
ev_owner = st.selectbox("EV Owner", ["Yes", "No"])
property_type_residential = st.selectbox("Property Type", ["Residential", "Other"])

# Add more features (region, day_of_week, month, etc.) as needed
month = st.slider("Month", 1, 12, 9)
day_of_week_Monday = st.checkbox("Is it Monday?")
day_of_week_Saturday = st.checkbox("Is it Saturday?")

# --- Encoding Inputs (match the training feature set) ---
input_dict = {
    'hour_of_day': hour_of_day,
    'temperature_c': temperature_c,
    'humidity_pct': humidity_pct,
    'solar_installed': 1 if solar_installed == "Yes" else 0,
    'ev_owner': 1 if ev_owner == "Yes" else 0,
    'property_type_residential': 1 if property_type_residential == "Residential" else 0,
    'month': month,
    'day_of_week_Monday': int(day_of_week_Monday),
    'day_of_week_Saturday': int(day_of_week_Saturday),
    # add other encoded variables if your model used them
}

# Convert to DataFrame
input_df = pd.DataFrame([input_dict])

# --- Predict ---
if st.button("Predict"):
    prediction = model.predict(input_df)[0]
    st.success(f"⚡ Estimated Power Consumption: **{prediction:.2f} kWh**")